/*
 * Catroid: An on-device visual programming system for Android devices
 * Copyright (C) 2010-2022 The Catrobat Team
 * (<http://developer.catrobat.org/credits>)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * An additional term exception under section 7 of the GNU Affero
 * General Public License, version 3, is available at
 * http://developer.catrobat.org/license_additional_term
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.catrobat.catroid.formulaeditor;

import com.danvexteam.lunoscript_annotations.LunoClass;

import org.catrobat.catroid.utils.EnumUtils;

import java.util.EnumSet;

@LunoClass
public enum Functions {

	SIN, COS, TAN, LN, LOG, SQRT, RAND, ROUND, ROUNDTO, ABS, PI, MOD, ARCSIN, ARCCOS, ARCTAN, ARCTAN2, EXP, POWER, FLOOR, CEIL,
	SIGN, LERP, MAP_RANGE, RGB, HSV, MIX_COLOR, TIMESTAMP, COLOR_ADD, COLOR_DARKEN, COLOR_LIGHTEN,
	CURRENT_STATE, STATE_TIME,
	MAX,
	MIN, TRUE, FALSE, LENGTH,
	LETTER, SUBTEXT, FILE, TO_HEX, TO_DEC, CLAMP, DISTAN, UPPER, LOWER, REVERSE, VAR, VARNAME, VARVALUE, RANDOM_STR, REPLACE, CONTAINS_STR, REPEAT, TABLE_X, TABLE_Y, TABLE_ELEMENT, TABLE_JOIN, JOIN, JOIN3, DISTANCE, REGEX, LIST_ITEM, CONTAINS, INDEX_OF_ITEM, NUMBER_OF_ITEMS,
	LUA, FLOATARRAY, VIEW_X, VIEW_Y, VIEW_WIDTH, VIEW_HEIGHT, VIDEO_PLAYING, VIDEO_TIME, JSON_GET, JSON_SET, JSON_IS_VALID,
	ARDUINOANALOG,
	ARDUINODIGITAL, RASPIDIGITAL,
	MULTI_FINGER_X, MULTI_FINGER_Y, MULTI_FINGER_TOUCHED, INDEX_CURRENT_TOUCH, COLLIDES_WITH_COLOR,

	COLOR_TOUCHES_COLOR, COLOR_AT_XY, COLOR_EQUALS_COLOR, TEXT_BLOCK_X, TEXT_BLOCK_Y,
	TEXT_BLOCK_SIZE, TEXT_BLOCK_FROM_CAMERA, TEXT_BLOCK_LANGUAGE_FROM_CAMERA, IF_THEN_ELSE, FLATTEN, CONNECT, FIND, TOUCHES_OBJECT_BY_NAME,

	GET_3D_POSITION_X,
	GET_3D_POSITION_Y,
	GET_3D_POSITION_Z,
	GET_3D_ROTATION_YAW,
	GET_3D_ROTATION_PITCH,
	GET_3D_ROTATION_ROLL,
	GET_3D_SCALE_X,
	GET_3D_SCALE_Y,
	GET_3D_SCALE_Z,
	GET_3D_DISTANCE,
	GET_DIRECTION_X,
	GET_DIRECTION_Y,
	GET_ANGLE,
	GET_RAY_DISTANCE,
	GET_RAY_HIT_OBJECT,
	GET_CAMERA_POS_X, GET_CAMERA_POS_Y, GET_CAMERA_POS_Z,
	GET_CAMERA_DIR_X, GET_CAMERA_DIR_Y, GET_CAMERA_DIR_Z,
	GET_CAMERA_ROTATION_YAW, GET_CAMERA_ROTATION_PITCH, GET_CAMERA_ROTATION_ROLL,
	GET_3D_VELOCITY_X, GET_3D_VELOCITY_Y, GET_3D_VELOCITY_Z,
	OBJECT_TOUCHES_OBJECT, OBJECT_INTERSECTS_OBJECT,
	GET_RAY_HIT_X, GET_RAY_HIT_Y, GET_RAY_HIT_Z, GET_RAY_HIT_NORMAL_X, GET_RAY_HIT_NORMAL_Y, GET_RAY_HIT_NORMAL_Z, RAY_DID_HIT,

	ID_OF_DETECTED_OBJECT, OBJECT_WITH_ID_VISIBLE,
	IS_MOUSE_BUTTON_DOWN,
	RAY_DID_HIT2,
	RAY_HIT_SPRITE_NAME,
	RAY_HIT_X,
	RAY_HIT_Y,
	RAY_HIT_DISTANCE, FILES_PATH, ALL_FILES, FILE_SIZE, DELTA, COLLISION_LIST, INTERSECT_LIST, PT_ARGMAX, PT_VALUE, PT_VALUEND, PT_SHAPE, PT_DUMP, PT_TOTALSIZE,
    F2D_X, F2D_Y, F2D_ROTATION, F2D_SCALE_X, F2D_SCALE_Y,
    F2D_COLOR_R, F2D_COLOR_G, F2D_COLOR_B, F2D_ALPHA,
    F2D_TEXTURE, F2D_CAM_X, F2D_CAM_Y, F2D_CAM_ZOOM,
    F2D_IS_TOUCHED, F2D_IS_TOUCHED_INDEX,  VOXEL_GET_ID, VOXEL_GET_DATA,

    FILE_EXISTS, DEVICE_NAME, DEVICE_MANUFACTURER, ANDROID_VERSION, API_LEVEL,
    SYSTEM_LANGUAGE, SYSTEM_THEME, CPU_NAME, CPU_ARCHITECTURE, CPU_CORES, CPU_FREQUENCY,
    TOTAL_RAM, FREE_RAM, TOTAL_STORAGE, FREE_STORAGE,
    BATTERY_PERCENT, BATTERY_CHARGING, BATTERY_TEMP, BATTERY_VOLTAGE, BATTERY_STATE,
    INTERNET_CONNECTED, INTERNET_TYPE, INTERNET_SPEED, LOCAL_IP, EXTERNAL_IP, GET_STATUS_CODE, DOWNLOAD_PROGRESS,
    SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_DPI, SCREEN_REFRESH, SCREEN_ORIENTATION,

    SPRITE_EXISTS, SPRITE_X, SPRITE_Y, SPRITE_SIZE, SPRITE_WIDTH, SPRITE_HEIGHT,
    SPRITE_DIRECTION, SPRITE_VISIBLE, SPRITE_TRANSPARENCY, SPRITE_LAYER,
    SPRITE_NAME_GET, SPRITE_INDEX_GET, SPRITE_UUID,
    SPRITE_CLONE_COUNT, SPRITE_LOOK_COUNT, SPRITE_SOUND_COUNT,
    SPRITE_VARIABLE_COUNT, SPRITE_LIST_COUNT,
    SPRITE_DISTANCE, SPRITE_TOUCHING, SPRITE_ANGLE_TO,
    SPRITE_RAGDOLLED,
    FILE_PROJECT_EXISTS, FILE_EXISTS_IN_DIR, FILE_EXISTS_AT_PATH,
    FILE_PROJECT_SIZE, FILE_SIZE_IN_DIR, FILE_SIZE_AT_PATH, FILE_READ_STRING,
    USED_RAM, USED_STORAGE, VOLUME_LEVEL, SCREEN_BRIGHTNESS, IS_IN_FOREGROUND,
    VOLUME_UP_HELD, VOLUME_DOWN_HELD, VOLUME_UP_HELD_SECONDS, VOLUME_DOWN_HELD_SECONDS,
    CPU_FREQUENCY_MIN, CPU_USAGE, GPU_NAME, OPENGL_VERSION, VULKAN_SUPPORTED,

    ADMOB_IS_INITIALIZED, ADMOB_IS_TEST_MODE, ADMOB_IS_BANNER_LOADED, ADMOB_IS_INTERSTITIAL_LOADED,
    ADMOB_IS_REWARDED_LOADED, ADMOB_IS_APP_OPEN_LOADED, ADMOB_LAST_ERROR_CODE, ADMOB_LAST_ERROR_MESSAGE,
    ADMOB_IS_GOOGLE_PLAY_SERVICES_AVAILABLE,

    CAMERA_X, CAMERA_Y, CAMERA_ROTATION, CAMERA_ZOOM,
    CHAR_TO_UNICODE, UNICODE_TO_CHAR, UNESCAPE_UTF,
    FILE_LAST_MODIFIED, FILE_MD5, FILE_SHA256,
    HTTP_RESPONSE_TEXT, HTTP_RESPONSE_CODE, HTTP_RESPONSE_HEADER, MQTT_MESSAGE,
    MEDIA_DURATION, IMAGE_WIDTH, IMAGE_HEIGHT,
    JOINNUMBER, PT_SAMPLE, SHA256, CLIPBOARD_TEXT,

    SHA_224, SHA_256, SHA_384, SHA_512, HASH_BYTES, HASH_FILE,
    AES_ENCRYPT, AES_DECRYPT, CHACHA20_ENCRYPT, CHACHA20_DECRYPT,
    PBKDF2, GENERATE_SALT, DERIVE_KEY,
    GENERATE_AES_KEY, GENERATE_RANDOM_BYTES, GENERATE_PASSWORD, GENERATE_UUID,
    RANDOM_HEX, RANDOM_BASE64, RANDOM_INT_SECURE, RANDOM_STRING_SECURE,
    BASE64_ENCODE, BASE64_DECODE, HEX_ENCODE, HEX_DECODE,
    COMPARE_HASH, IS_BASE64, IS_HEX,
    HMAC_SHA_256, HMAC_SHA_512,
            RSA_GENERATE_KEY_PAIR, RSA_ENCRYPT, RSA_DECRYPT, RSA_SIGN, RSA_VERIFY, IS_PC, IS_MOBILE,

    TILE_AT_POSITION, IS_SOLID_TILE_AT, TILEMAP_WIDTH, TILEMAP_HEIGHT, TILE_SIZE,

    GET_ITEM,

    SCENE_LAUNCH_COUNT,

    LIST_SLICE, RGB_TO_HEX, HEX_TO_RGB, LIST_SUM, LIST_AVERAGE, LIST_MIN, LIST_MAX,
    FILE_TO_BASE64, MD5, NOTIFICATION_REPLY, READ_FILE,
    SEED, CLIPBOARD_PASTE, LIST_RANDOM_ITEM;

	private static final String TAG = Functions.class.getSimpleName();
	public static EnumSet<Functions> TEXT = EnumSet.of(INTERSECT_LIST, COLLISION_LIST, DELTA, LENGTH, LETTER, SUBTEXT, CLAMP, TO_HEX, TO_DEC, DISTAN, UPPER, LOWER, REVERSE, VAR, VARNAME, VARVALUE, JOIN, JOIN3, REPLACE, CONTAINS_STR, REPEAT, RANDOM_STR,
			REGEX, TABLE_X, TABLE_Y, TABLE_ELEMENT, TABLE_JOIN, FLOATARRAY, LUA, VIEW_X, VIEW_Y, VIEW_WIDTH, VIEW_HEIGHT, VIDEO_PLAYING, VIDEO_TIME, FILE, FILES_PATH, ALL_FILES, FILE_SIZE,
			GET_3D_POSITION_X, GET_3D_POSITION_Y, GET_3D_POSITION_Z, GET_3D_ROTATION_YAW, GET_3D_ROTATION_PITCH, GET_3D_ROTATION_ROLL, GET_3D_SCALE_X, GET_3D_SCALE_Y, GET_3D_SCALE_Z, GET_3D_DISTANCE, GET_DIRECTION_X, GET_DIRECTION_Y, GET_ANGLE,
			GET_RAY_DISTANCE, GET_RAY_HIT_OBJECT, GET_CAMERA_POS_X, GET_CAMERA_POS_Y, GET_CAMERA_POS_Z, GET_CAMERA_DIR_X, GET_CAMERA_DIR_Y, GET_CAMERA_DIR_Z,
			GET_3D_VELOCITY_X, GET_3D_VELOCITY_Y, GET_3D_VELOCITY_Z, GET_CAMERA_ROTATION_YAW, GET_CAMERA_ROTATION_PITCH, GET_CAMERA_ROTATION_ROLL, OBJECT_TOUCHES_OBJECT, JSON_GET, JSON_SET, JSON_IS_VALID, GET_RAY_HIT_X, GET_RAY_HIT_Y, GET_RAY_HIT_Z, GET_RAY_HIT_NORMAL_X, GET_RAY_HIT_NORMAL_Y, GET_RAY_HIT_NORMAL_Z,
			IS_MOUSE_BUTTON_DOWN, OBJECT_INTERSECTS_OBJECT, PT_ARGMAX, PT_VALUE, PT_VALUEND, PT_SHAPE, PT_DUMP, PT_TOTALSIZE,
            F2D_X, F2D_Y, F2D_ROTATION, F2D_SCALE_X, F2D_SCALE_Y,
            F2D_COLOR_R, F2D_COLOR_G, F2D_COLOR_B, F2D_ALPHA,
            F2D_TEXTURE, F2D_CAM_X, F2D_CAM_Y, F2D_CAM_ZOOM,
            F2D_IS_TOUCHED, F2D_IS_TOUCHED_INDEX,  VOXEL_GET_ID, VOXEL_GET_DATA,
            FILE_EXISTS, DEVICE_NAME, DEVICE_MANUFACTURER, ANDROID_VERSION,
            SYSTEM_LANGUAGE, SYSTEM_THEME, CPU_NAME, CPU_ARCHITECTURE,
            BATTERY_STATE, INTERNET_TYPE, LOCAL_IP, EXTERNAL_IP, SCREEN_ORIENTATION, GET_STATUS_CODE, DOWNLOAD_PROGRESS,

            SPRITE_NAME_GET, SPRITE_UUID,
            CURRENT_STATE,
            FILE_PROJECT_SIZE, FILE_SIZE_IN_DIR, FILE_SIZE_AT_PATH, FILE_READ_STRING,
            SCENE_LAUNCH_COUNT,
    USED_RAM, USED_STORAGE, VOLUME_LEVEL, SCREEN_BRIGHTNESS, IS_IN_FOREGROUND,
    VOLUME_UP_HELD, VOLUME_DOWN_HELD, VOLUME_UP_HELD_SECONDS, VOLUME_DOWN_HELD_SECONDS,
            CPU_FREQUENCY_MIN, CPU_USAGE, GPU_NAME, OPENGL_VERSION, VULKAN_SUPPORTED,
            IS_PC, IS_MOBILE,
            ADMOB_LAST_ERROR_MESSAGE,
            TILE_AT_POSITION, IS_SOLID_TILE_AT, TILEMAP_WIDTH, TILEMAP_HEIGHT, TILE_SIZE,
            SHA_224, SHA_256, SHA_384, SHA_512, HASH_BYTES, HASH_FILE,
            AES_ENCRYPT, AES_DECRYPT, CHACHA20_ENCRYPT, CHACHA20_DECRYPT,
            PBKDF2, GENERATE_SALT, DERIVE_KEY,
            GENERATE_AES_KEY, GENERATE_RANDOM_BYTES, GENERATE_PASSWORD, GENERATE_UUID,
            RANDOM_HEX, RANDOM_BASE64, RANDOM_STRING_SECURE,
            BASE64_ENCODE, BASE64_DECODE, HEX_ENCODE, HEX_DECODE,
            HMAC_SHA_256, HMAC_SHA_512,
            RSA_GENERATE_KEY_PAIR, RSA_ENCRYPT, RSA_DECRYPT, RSA_SIGN, RSA_VERIFY,
            RGB_TO_HEX, HEX_TO_RGB, LIST_SUM, LIST_AVERAGE, LIST_MIN, LIST_MAX,
            FILE_TO_BASE64, MD5, NOTIFICATION_REPLY, READ_FILE,
            JOINNUMBER, HTTP_RESPONSE_TEXT, HTTP_RESPONSE_CODE, HTTP_RESPONSE_HEADER,
            CAMERA_X, CAMERA_Y, CAMERA_ROTATION, CAMERA_ZOOM, CLIPBOARD_TEXT, MQTT_MESSAGE,
            SHA256, FILE_MD5, FILE_SHA256, PT_SAMPLE, CHAR_TO_UNICODE, UNICODE_TO_CHAR, UNESCAPE_UTF,
            SEED, CLIPBOARD_PASTE, LIST_RANDOM_ITEM);
	public static final EnumSet<Functions> LIST = EnumSet.of(LIST_ITEM, CONTAINS, INDEX_OF_ITEM,
			NUMBER_OF_ITEMS, FLATTEN, CONNECT, FIND, LIST_SLICE, LIST_SUM, LIST_AVERAGE, LIST_MIN, LIST_MAX,
			LIST_RANDOM_ITEM);
	public static final EnumSet<Functions> BOOLEAN = EnumSet.of(TRUE, FALSE, CONTAINS,
			MULTI_FINGER_TOUCHED, COLLIDES_WITH_COLOR, COLOR_TOUCHES_COLOR, COLOR_EQUALS_COLOR, RAY_DID_HIT, OBJECT_INTERSECTS_OBJECT, OBJECT_TOUCHES_OBJECT,
			FILE_EXISTS, FILE_PROJECT_EXISTS, FILE_EXISTS_IN_DIR, FILE_EXISTS_AT_PATH,
			BATTERY_CHARGING, INTERNET_CONNECTED, IS_IN_FOREGROUND, VULKAN_SUPPORTED,
			SPRITE_EXISTS, SPRITE_VISIBLE, SPRITE_TOUCHING, SPRITE_RAGDOLLED,
			IS_PC, IS_MOBILE,
			F2D_IS_TOUCHED, F2D_IS_TOUCHED_INDEX,
			ADMOB_IS_INITIALIZED, ADMOB_IS_TEST_MODE, ADMOB_IS_BANNER_LOADED, ADMOB_IS_INTERSTITIAL_LOADED,
			ADMOB_IS_REWARDED_LOADED, ADMOB_IS_APP_OPEN_LOADED, ADMOB_IS_GOOGLE_PLAY_SERVICES_AVAILABLE,
			COMPARE_HASH, IS_BASE64, IS_HEX, RSA_VERIFY,
			IS_SOLID_TILE_AT);

	public static boolean isFunction(String value) {
		return EnumUtils.isValidEnum(Functions.class, value);
	}

	public static boolean isBoolean(Functions function) {
		return BOOLEAN.contains(function);
	}

	public static Functions getFunctionByValue(String value) {
		return EnumUtils.getEnum(Functions.class, value);
	}

	public static void addText(Functions func) {
		TEXT.add(func);
	}
}
