name: AI Feature Build (Test APK)

on:
  workflow_dispatch:
    inputs:
      feature_name:
        description: 'Feauture name'
        required: true
        default: 'AI-Feature'

jobs:
  build:
    name: Build AI APK
    runs-on: ubuntu-latest

    env:
      _JAVA_OPTIONS: "-Xmx5g"
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx5g -Dorg.gradle.workers.max=2"

    steps:
      - name: Скачиваем код (Checkout)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Настраиваем Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Настраиваем Gradle кэш
        uses: gradle/gradle-build-action@v2

      - name: Настраиваем проект (applicationId, Firebase)
        run: |
          sed -i 's/applicationId "org.DanVexTeam.NewCatroid"/applicationId "org.DanVexTeam.NewCatroid.aitest"/g' catroid/build.gradle
          
          find . -name "google-services*.json" -exec sed -i 's/"org.DanVexTeam.NewCatroid"/"org.DanVexTeam.NewCatroid.aitest"/g' {} +
          
          find catroid/src -type f -name "*.java" -exec sed -i 's/com.pdrogfer.mididroid/com.leff.midi/g' {} +
          find catroid/src -type f -name "*.java" -exec sed -i 's/com.oliewa92.mididroid/com.leff.midi/g' {} +
          
          echo "Пакет изменен, Firebase изменен"

      - name: Даем права на исполнение Gradle
        run: chmod +x ./gradlew

      - name: Компилируем APK (Danvex Debug)
        run: ./gradlew assembleDanvexDebug --stacktrace

      - name: Загружаем готовый APK в Artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: NewCatroid-${{ github.event.inputs.feature_name }}
          path: '**/build/outputs/apk/danvex/debug/*.apk'
          retention-days: 7
